-- Add shortlisted flag to prospects
ALTER TABLE prospects ADD COLUMN IF NOT EXISTS shortlisted boolean DEFAULT false;

-- Sequences generated by Claude for each shortlisted prospect
CREATE TABLE IF NOT EXISTS shortlist_sequences (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  prospect_id uuid REFERENCES prospects(id) ON DELETE CASCADE,
  research_context text,
  sequences jsonb,  -- { email: [{step,subject,body}x5], linkedin: [{step,message}x5] }
  model_used text,
  generated_at timestamptz
);

ALTER TABLE shortlist_sequences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all on shortlist_sequences" ON shortlist_sequences FOR ALL USING (true) WITH CHECK (true);
